/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class TTT extends javax.swing.JFrame {

    /**
     * Creates new form TTT
     */
    
    int cnt=0;
    public TTT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        P1 = new javax.swing.JTextField();
        P2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        J1 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        srt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));

        B1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Name.setText("Tic Tac Toe");

        B4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        P1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        P2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        P2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Player 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Player 2");

        J1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        J1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        J2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        J2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        J2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Enter the players name here:");

        srt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        srt.setText("START");
        srt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srtActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(B1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                            .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(B7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(B2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(B5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(B8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(B3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(B6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(P2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(srt)
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srt)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 int a=0;
   void fu()
  { B1.setBackground(new java.awt.Color(255, 0, 0));
    B2.setBackground(new java.awt.Color(255, 0, 0));
    B3.setBackground(new java.awt.Color(255, 0, 0));
    B4.setBackground(new java.awt.Color(255, 0, 0));
    B5.setBackground(new java.awt.Color(255, 0, 0));
    B6.setBackground(new java.awt.Color(255, 0, 0));
    B7.setBackground(new java.awt.Color(255, 0, 0));
    B8.setBackground(new java.awt.Color(255, 0, 0));
    B9.setBackground(new java.awt.Color(255, 0, 0));
    }
 int func()
    {
        if(B1.getText().equals(B2.getText()) && (B2.getText().equals(B3.getText())))
        {   
       
            if(B1.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins"); fu();
            J1.setText("");
            return 1;
            }
            
            else if(B1.getText().equals("O"))
            { J2.setText(P2.getText()+ " wins"); fu();
             J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B4.getText().equals(B5.getText()) && (B5.getText().equals(B6.getText())))
        {
            if(B4.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else if(B4.getText().equals("O"))
            { J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B7.getText().equals(B8.getText()) && (B8.getText().equals(B9.getText())))
        {    
            if(B7.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else if(B7.getText().equals("O"))
            {  J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B1.getText().equals(B5.getText()) && (B5.getText().equals(B9.getText())))
        {   
            if(B1.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins");fu();
            J1.setText(""); return 1;
            }
            else if(B1.getText().equals("O"))
            { J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B3.getText().equals(B5.getText()) && (B5.getText().equals(B7.getText())))
        {     
            if(B3.getText().equals("X"))
            { J2.setText(P1.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else if(B3.getText().equals("O"))
            { J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B1.getText().equals(B4.getText()) && (B4.getText().equals(B7.getText())))
        {    
            if(B1.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else if(B1.getText().equals("O"))
            {J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B2.getText().equals(B5.getText()) && (B5.getText().equals(B8.getText())))
        {   
            if(B2.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else if(B2.getText().equals("O"))
            {J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(B3.getText().equals(B6.getText()) && (B6.getText().equals(B9.getText())))
        {   
            if(B3.getText().equals("X"))
            {J2.setText(P1.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else if(B3.getText().equals("O"))
            { J2.setText(P2.getText()+ " wins");fu();
            J1.setText("");return 1;
            }
            else{}
            
        }
        else if(cnt==8)
        {
            J2.setText("The Match is draw");
            J1.setText("");return 1;
        }   
        return 0;
    }
    
    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B1.setText("X");
        else
        B1.setText("O");
         a = func();   
         
         if(a!=1)
         {
            if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
         }  
       
    }//GEN-LAST:event_B1ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B3.setText("X");
        else
        B3.setText("O");
        
        a = func();
        
        if(a!=1)
        {
            if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }  
        
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B4.setText("X");
        else
        B4.setText("O");
        
       a = func();
      
       if(a!=1)
       {     if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
       }    
        
    }//GEN-LAST:event_B4ActionPerformed
  
    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B6.setText("X");
        else
        B6.setText("O");
        
       a = func();
        
        if(a!=1)
        {
        if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }
    }//GEN-LAST:event_B6ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_P1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B2.setText("X");
        else
        B2.setText("O");
        
        a = func();
        
        if(a!=1)
        {
        if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }
    }//GEN-LAST:event_B2ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B5.setText("X");
        else
        B5.setText("O");
        
        a = func();
        
        if(a!=1)
        {
        if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }
    }//GEN-LAST:event_B5ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B7.setText("X");
        else
        B7.setText("O");
        
        a = func();
        
        if(a!=1)
        {
        if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B8.setText("X");
        else
        B8.setText("O");
        
        a = func();
        
        if(a!=1)
        {
        if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        B9.setText("X");
        else
        B9.setText("O");
        
        a = func();
        if(a!=1)
        {
        if((++cnt)%2==0)
               J1.setText("It is "+P1.getText() + "'s turn");
             else
               J1.setText("It is "+P2.getText() + "'s turn");
        }
    }//GEN-LAST:event_B9ActionPerformed

    private void srtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srtActionPerformed
        // TODO add your handling code here:
        if(cnt%2==0)
        J1.setText("It is "+P1.getText() + "'s turn");
        else
        J1.setText("It is "+P2.getText() + "'s turn");    
    }//GEN-LAST:event_srtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTT().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JLabel J1;
    private javax.swing.JLabel J2;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField P1;
    private javax.swing.JTextField P2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton srt;
    // End of variables declaration//GEN-END:variables
}
